apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wcbsos617-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wcbsos617-java-quarkus-gitops